### ISSUE TITLE
Deploy clound-harness app and populate

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/asu-olfactory#20]

**Comment by zsinnema** [comment]
@enicolasgomez check this out: https://github.com/MetaCell/cloud-harness/blob/develop/docs/applications/databases.md#configuring-a-database

the thing you need is to create a custom postgresql image (Dockerfile) install the needed modules and then reference this image in you application values.yaml file 


put your custom postgresql image Dockerfile in this folder: <project>/infrastructure/base-images/
e.g.
```
mkdir -p infrastructure/base-images/asu-olf-postgresql
echo "FROM postgres:13" >  infrastructure/base-images/asu-olf-postgresql/Dockerfile
```
and then change the new Dockerfile according to your needs (change the PostgreSQL version, add modules etc)


after this reference in your application that you want to use this custom postgresql image
to do this use the `image_ref` setting in values.yaml

**Comment by filippomc** [comment]
https://github.com/MetaCell/asu-olfactory/blob/master/infrastructure/base-images/pubchem-postgres/Dockerfile only need to edit this file to add the module and [this configuration](https://github.com/MetaCell/asu-olfactory/blob/65f0c38c66d075ccf4a6d120ca80e8e74e4ac357/applications/pub-chem-index/deploy/values.yaml#L11) is already set up to load that database image.
Need to use latest dev of cloudharness
