### ISSUE TITLE
Move client to Nginx

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/asu-olfactory#30]
To avoid using a proxy and following cloud harness best practices, we should move the client side code to 
https://hub.docker.com/_/nginx
so static content is being server from the same URL avoiding any CORS issue or proying.

**Comment by enicolasgomez** [comment]
@jrmartin after moving the client to codefresh some new issues rised:
https://g.codefresh.io/build/62fcdee8dc86043bf6a024f7?step=prepare_deployment&tab=output&logs=terminal

Should check with @zsinnema and @filippomc

**Comment by filippomc** [comment]
This comes from a mismatch in the cloudharness version.

To fix, run `harness-deployment ... -e dev` locally to update the codefresh script and push it
