### ISSUE TITLE
Parsing Issue with CID-Title

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/asu-olfactory#45]
When parsing CID-Title with populatetable_parallel.py script, we have an issue parsing the text for CID-Title:

`[main]         
[main] /usr/local/lib/python3.9/site-packages/aiopg/pool.py:478: ResourceWarning: Unclosed 1 connections in <aiopg.pool.Pool object at 0x7ff94469abe0>
[main]   warnings.warn(
[main] 2022-10-04 17:52:25,524 [INFO] populate_parallel.go: Ouput folder %s /tmp/CID/CID-Title/
[main] Traceback (most recent call last):
[main]   File "/populate_parallel.py", line 157, in <module>
[main]     loop.run_until_complete(go())  
[main]   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[main]     return future.result()
[main]   File "/populate_parallel.py", line 150, in go
[main]     df.to_csv(output + "export-*.csv", sep='\t', index=False)
[main]   File "/usr/local/lib/python3.9/site-packages/dask/dataframe/core.py", line 1705, in to_csv
[main]     return to_csv(self, filename, **kwargs)
[main]   File "/usr/local/lib/python3.9/site-packages/dask/dataframe/io/csv.py", line 972, in to_csv
[main]     return list(dask.compute(*values, **compute_kwargs))
[main]   File "/usr/local/lib/python3.9/site-packages/dask/base.py", line 600, in compute
[main]     results = schedule(dsk, keys, **kwargs)
[main]   File "/usr/local/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
[main]     results = get_async(
[main]   File "/usr/local/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
[main]     raise_exception(exc, tb)
[main]   File "/usr/local/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
[main]     raise exc
[main]   File "/usr/local/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
[main]     result = _execute_task(task, data)
[main]   File "/usr/local/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
[main]     return func(*(_execute_task(a, cache) for a in args))
[main]   File "/usr/local/lib/python3.9/site-packages/dask/optimization.py", line 990, in __call__
[main]     return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
[main]   File "/usr/local/lib/python3.9/site-packages/dask/core.py", line 149, in get
[main]     result = _execute_task(task, cache)
[main]   File "/usr/local/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
[main]     return func(*(_execute_task(a, cache) for a in args))
[main]   File "/usr/local/lib/python3.9/site-packages/dask/dataframe/io/csv.py", line 129, in __call__
[main]     df = pandas_read_text(
[main]   File "/usr/local/lib/python3.9/site-packages/dask/dataframe/io/csv.py", line 182, in pandas_read_text
[main]     df = reader(bio, **kwargs)
[main]   File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[main]     return func(*args, **kwargs)
[main]   File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 317, in wrapper
[main]     return func(*args, **kwargs)
[main]   File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[main]     return _read(filepath_or_buffer, kwds)
[main]   File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
[main]     return parser.read(nrows)
[main]   File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1772, in read
[main]     ) = self._engine.read(  # type: ignore[attr-defined]
[main]   File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 243, in read
[main]     chunks = self._reader.read_low_memory(nrows)
[main]   File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
[main]   File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader._read_rows
[main]   File "pandas/_libs/parsers.pyx", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
[main]   File "pandas/_libs/parsers.pyx", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
[main]   File "pandas/_libs/parsers.pyx", line 1159, in pandas._libs.parsers.TextReader._convert_with_dtype
[main]   File "pandas/_libs/parsers.pyx", line 1246, in pandas._libs.parsers.TextReader._string_convert
[main]   File "pandas/_libs/parsers.pyx", line 1444, in pandas._libs.parsers._string_box_utf8
[main] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte
`

**Comment by rgerkin** [comment]
What encoding are you using?  You may need to try `latin1` or `utf-16` instead of `utf-8`.

**Comment by jrmartin** [comment]
@rgerkin Thanks! `latin` worked for CID-Title.
