### ISSUE TITLE
Fixing Deployment Issues , Improvements

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/asu-olfactory#53]
- [x]  Sort results, exact match on top
- [x]  Exact match, true/false, missing on results returned for /properties endpoints
- [x] If exact=true passed as parameter on URL, only return exact matches. If none, then return zero
- [x] Truncate table names passed as properties and returned as results
- [x]  Remove CIDS from /properties results, only leave the one
![image](https://user-images.githubusercontent.com/4562825/202796577-78e5b527-d939-40dc-9889-f6b6fec63349.png)

**Comment by enicolasgomez** [comment]
@jrmartin we need to add XSS filtering to anything that get's feed and concatenated into SQL

https://stackoverflow.com/questions/901369/python-library-for-xss-filtering

**Comment by jrmartin** [comment]
@rgerkin @enicolasgomez The requests made during the last call have been deployed. 

We can now use a query parameter to only get the exact match results:
Examples:
https://pubchem.olfactory.dev.metacell.us/molecules/mesh/chlorin?exactMatch=True
https://pubchem.olfactory.dev.metacell.us/molecules/mesh/chlorin/properties/synonym_filtered,title,iupac?exactMatch=True

By default, not using the query parameter will return all results regardless of exact match.
E.g.
https://pubchem.olfactory.dev.metacell.us/molecules/mesh/chlorin
https://pubchem.olfactory.dev.metacell.us/molecules/mesh/chlorin?exactMatch=False

A more detailed documentation can be found on the main page [ReadMe](https://github.com/MetaCell/asu-olfactory/tree/feature/53#readme)
